"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { BackButton } from "@/app/components/back-button";
import { cn, Icon, PrimaryButton, SecondaryButton } from "@/app/components/ui";
import { ApiError } from "@/services/apiClient";
import { clearPendingAskFile, getPendingAskFile, setPendingAskFile } from "@/services/ask-upload-store";
import type { AskDocumentMessage } from "@/services/dtos/ask";
import { useAskDocument, useAskDocumentMessages, useAskDocuments, useAskSessions, useDeleteAskDocument, useRenameAskDocument, useSendAskDocumentMessage, useUploadAskDocument } from "@/services/hooks/useAsk";

const PRIMARY_SUBJECTS = ["English", "Mathematics", "Social Studies", "Business", "History", "Health", "Geography", "Biology"];
const EXTRA_SUBJECTS = ["Physics", "Chemistry", "Computers and Technology", "Arts", "World Languages", "Spanish", "French", "German", "AP", "SAT", "Medicine", "Law", "Engineering"];

function Header({ title, subtitle }: { title: string; subtitle?: string }) {
  return <header className="flex items-center gap-3"><BackButton /><div className="min-w-0"><h1 className="truncate text-2xl font-black text-[#0F1626]">{title}</h1>{subtitle && <p className="truncate text-sm font-semibold text-slate-500">{subtitle}</p>}</div></header>;
}

function SkeletonRows() { return <div className="space-y-3" aria-label="Loading"><div className="h-16 animate-pulse rounded-2xl bg-slate-200"/><div className="h-16 animate-pulse rounded-2xl bg-slate-200"/><div className="h-16 animate-pulse rounded-2xl bg-slate-200"/></div>; }
function query(values: Record<string, string>) { return new URLSearchParams(values).toString(); }
function stripExtension(name: string) { return name.replace(/\.[^.]+$/, ""); }
function getErrorMessage(error: unknown) { if(error instanceof ApiError && error.data && typeof error.data === "object" && "detail" in error.data) return String(error.data.detail); return error instanceof Error ? error.message : "Please try again."; }
function isPremiumRequired(error: unknown) { return error instanceof ApiError && (error.status === 402 || error.status === 403); }
function isRateLimited(error: unknown) { return error instanceof ApiError && error.status === 429; }

export function AskHub() {
  const router=useRouter(); const docs=useAskDocuments(); const sessions=useAskSessions(); const [tab,setTab]=useState<"docs"|"sessions">("docs"); const [picker,setPicker]=useState(false); const input=useRef<HTMLInputElement>(null); const camera=useRef<HTMLInputElement>(null);
  function picked(file?:File){if(!file)return;setPendingAskFile(file);router.push(`/ask/new?${query({name:file.name,mimeType:file.type||"application/octet-stream"})}`);}
  const list=tab==="docs"?docs:sessions;
  return <div className="mx-auto max-w-3xl space-y-6 pb-24"><Header title="Ask My Docs"/><div className="relative grid grid-cols-2 border-b border-slate-200"><button className={cn("pb-3 text-sm font-black",tab==="docs"?"text-[#312E81]":"text-slate-400")} onClick={()=>setTab("docs")}>My Docs</button><button className={cn("pb-3 text-sm font-black",tab==="sessions"?"text-[#312E81]":"text-slate-400")} onClick={()=>setTab("sessions")}>My Sessions</button><span className={cn("absolute bottom-0 h-0.5 w-1/2 bg-[#312E81] transition-transform duration-300",tab==="sessions"&&"translate-x-full")}/></div>
    {list.isLoading?<SkeletonRows/>:list.isError?<Empty icon="warning" title="Couldn’t load this list" copy="Check your connection and try again."/>:tab==="docs"?(docs.data?.items.length?<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{docs.data.items.map(doc=><button className="flex min-h-16 w-full items-center gap-3 border-b border-slate-100 px-4 text-left last:border-0 hover:bg-slate-50" key={doc.id} onClick={()=>router.push(`/ask/document?id=${encodeURIComponent(doc.id)}`)}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#EEF2FF] text-[#312E81]"><Icon name="file" className="h-5 w-5"/></span><b className="min-w-0 flex-1 truncate">{doc.name}</b><Icon name="chevronRight" className="h-4 w-4 text-slate-300"/></button>)}</div>:<Empty icon="file" title="No documents yet" copy="Add a document and ask questions about anything inside."/>):(sessions.data?.items.length?<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{sessions.data.items.map(session=><button className="flex min-h-18 w-full items-center gap-3 border-b border-slate-100 px-4 text-left last:border-0 hover:bg-slate-50 disabled:cursor-default" disabled={session.kind!=="document"} key={session.id} onClick={()=>router.push(`/ask/session?${query({docId:session.id,docName:session.title})}`)}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#FEFCE8] text-[#CA8A04]"><Icon name={session.kind==="document"?"file":"chat"} className="h-5 w-5"/></span><span className="min-w-0 flex-1"><b className="block truncate">{session.title}</b><small className="font-semibold text-slate-500">{session.kind==="document"?"Document":"Question"} · {timeAgo(session.created_at)}</small></span><Icon name="chevronRight" className="h-4 w-4 text-slate-300"/></button>)}</div>:<Empty icon="chat" title="No sessions yet" copy="Your document conversations will appear here."/>)}
    {tab==="docs"&&<button className="fixed bottom-[82px] left-1/2 z-20 -translate-x-1/2 rounded-full bg-[#FACC15] px-6 py-3 text-sm font-black text-[#1E1B4B] shadow-xl lg:bottom-7 lg:left-[calc(50%+9rem)]" onClick={()=>setPicker(true)}><Icon name="create" className="mr-2 inline h-4 w-4"/>Add document</button>}
    <input accept="application/pdf,image/*,text/plain" className="hidden" onChange={e=>{picked(e.target.files?.[0]);e.target.value="";}} ref={input} type="file"/><input accept="image/*" capture="environment" className="hidden" onChange={e=>{picked(e.target.files?.[0]);e.target.value="";}} ref={camera} type="file"/>
    {picker&&<UploadPicker onClose={()=>setPicker(false)} onFile={()=>{setPicker(false);input.current?.click();}} onCamera={()=>{setPicker(false);camera.current?.click();}}/>}
  </div>;
}

function Empty({icon,title,copy}:{icon:Parameters<typeof Icon>[0]["name"];title:string;copy:string}){return <div className="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-100 text-slate-500"><Icon name={icon} className="h-6 w-6"/></span><h2 className="mt-4 text-lg font-black">{title}</h2><p className="mx-auto mt-2 max-w-sm text-sm font-semibold text-slate-500">{copy}</p></div>;}
function UploadPicker({onClose,onFile,onCamera}:{onClose:()=>void;onFile:()=>void;onCamera:()=>void}){return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 p-3 sm:items-center sm:justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="w-full rounded-3xl bg-white p-6 shadow-xl sm:max-w-md"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Add a document</h2><button aria-label="Close" onClick={onClose}><Icon name="x" className="h-5 w-5"/></button></div><p className="mt-2 text-sm font-semibold text-slate-500">PDF, image, or plain text.</p><div className="mt-5 grid grid-cols-3 gap-3"><PickerButton icon="file" label="File" onClick={onFile}/><PickerButton icon="image" label="Library" onClick={onFile}/><PickerButton icon="camera" label="Camera" onClick={onCamera}/></div></div></div>;}
function PickerButton({icon,label,onClick}:{icon:Parameters<typeof Icon>[0]["name"];label:string;onClick:()=>void}){return <button className="rounded-2xl border border-slate-200 p-4 font-black hover:border-[#818CF8] hover:bg-[#EEF2FF]" onClick={onClick}><Icon name={icon} className="mx-auto mb-2 h-6 w-6"/><span className="text-sm">{label}</span></button>;}

export function AskNewDocument() {
  const router=useRouter();const search=useSearchParams();const file=getPendingAskFile();const original=search.get("name")??"";const [name,setName]=useState(stripExtension(original));const [subject,setSubject]=useState("");const [more,setMore]=useState(false);const [error,setError]=useState("");const upload=useUploadAskDocument();const subjects=more?[...PRIMARY_SUBJECTS,...EXTRA_SUBJECTS]:PRIMARY_SUBJECTS;
  function submit(){if(!file||!name.trim()||!subject)return;setError("");upload.mutate({file,name:name.trim(),subject},{onSuccess:doc=>{clearPendingAskFile();router.replace(`/ask/document?id=${encodeURIComponent(doc.id)}`);},onError:err=>{console.warn("[ask-upload]",err);setError(`Upload failed: ${getErrorMessage(err)}`);}});}
  return <div className="mx-auto max-w-3xl space-y-8 pb-24"><Header title="New document"/>{!file&&<p className="rounded-2xl bg-amber-50 p-4 text-sm font-semibold text-amber-800">The selected file is no longer available. Go back and choose it again.</p>}<section><label className="text-xs font-black uppercase tracking-[.16em] text-slate-500">Document name</label><input className="mt-3 h-13 w-full rounded-2xl border border-slate-300 bg-white px-4 text-lg font-bold outline-none focus:border-[#312E81] focus:ring-4 focus:ring-[#312E81]/10" onChange={e=>setName(e.target.value)} value={name}/></section><section><h2 className="text-xl font-black">What&apos;s the subject?</h2><div className="mt-4 flex flex-wrap gap-2">{subjects.map(item=><button className={cn("rounded-full border px-4 py-2.5 text-sm font-black transition",subject===item?"border-[#312E81] bg-[#312E81] text-white":"border-slate-200 bg-white hover:border-[#818CF8]")} key={item} onClick={()=>setSubject(item)}>{item}</button>)}{!more&&<button className="rounded-full border border-dashed border-[#818CF8] px-4 py-2.5 text-sm font-black text-[#312E81]" onClick={()=>setMore(true)}>See more</button>}</div></section>{error&&<p className="rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<div className="fixed inset-x-0 bottom-[73px] z-20 border-t border-slate-200 bg-white/95 p-3 lg:bottom-0 lg:left-72"><PrimaryButton className="mx-auto flex w-full max-w-3xl rounded-2xl" disabled={!file||!name.trim()||!subject||upload.isPending} onClick={submit}>{upload.isPending?<span className="h-4 w-28 animate-pulse rounded bg-white/50"/>:"Start Session"}</PrimaryButton></div></div>;
}

export function AskDocumentViewer() {
  const router=useRouter();const id=useSearchParams().get("id")??"";const doc=useAskDocument(id);const rename=useRenameAskDocument();const remove=useDeleteAskDocument();const [menu,setMenu]=useState(false);const [renaming,setRenaming]=useState(false);const [newName,setNewName]=useState("");
  if(doc.isLoading)return <div className="space-y-4"><div className="h-12 animate-pulse rounded-xl bg-slate-200"/><div className="h-[65vh] animate-pulse rounded-3xl bg-slate-200"/></div>;if(doc.isError||!doc.data)return <Empty icon="warning" title="Document not found" copy="It may have been deleted or moved."/>;
  const data=doc.data;const url=normalizeFileUrl(data.file_url);const title=stripExtension(data.name);
  function doRename(){const value=newName.trim();if(!value)return;rename.mutate({id,name:value},{onSuccess:()=>{setRenaming(false);setMenu(false);}});}
  function doDelete(){if(!window.confirm("Delete document? This cannot be undone."))return;remove.mutate(id,{onSuccess:()=>router.back()});}
  return <div className="-mx-4 -my-6 flex min-h-[calc(100vh-5rem)] flex-col sm:-mx-6 lg:-mx-8 lg:-my-10"><header className="relative z-20 flex items-center justify-between border-b border-white/60 bg-white/80 px-4 py-3 backdrop-blur-xl"><BackButton variant="ghost"/><div className="min-w-0 px-3 text-center"><h1 className="truncate font-black">{title}</h1><p className="text-xs font-semibold text-slate-500">{data.pages.length} page{data.pages.length===1?"":"s"}</p></div><button className="grid h-11 w-11 place-items-center rounded-full bg-slate-100 font-black" onClick={()=>setMenu(v=>!v)} aria-label="Document actions">•••</button>{menu&&<div className="absolute right-4 top-16 w-48 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><button className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold hover:bg-slate-50" onClick={()=>{setNewName(title);setRenaming(true);}}>Rename</button><button className="w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold text-red-600 hover:bg-red-50" onClick={doDelete}>Delete</button></div>}</header><main className="relative flex-1 bg-slate-200">{url?<iframe className="absolute inset-0 h-full w-full border-0" src={url} title={data.name}/>:<div className="grid h-full min-h-96 place-items-center p-8 text-center"><div><Icon name="warning" className="mx-auto h-8 w-8 text-amber-500"/><h2 className="mt-3 font-black">Preview unavailable</h2><p className="mt-2 text-sm text-slate-500">The server returned a local file URL.</p></div></div>}</main><div className="fixed bottom-[82px] left-1/2 z-20 -translate-x-1/2 lg:bottom-7 lg:left-[calc(50%+9rem)]"><PrimaryButton className="rounded-full px-7 shadow-xl" onClick={()=>router.push(`/ask/session?${query({docId:id,docName:data.name})}`)}>Start Session <Icon name="arrowUp" className="h-4 w-4 rotate-90"/></PrimaryButton></div>{renaming&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form className="w-full max-w-md rounded-3xl bg-white p-6" onSubmit={e=>{e.preventDefault();doRename();}}><h2 className="text-xl font-black">Rename document</h2><input autoFocus className="mt-4 h-12 w-full rounded-xl border px-4" onChange={e=>setNewName(e.target.value)} value={newName}/><div className="mt-4 flex gap-3"><SecondaryButton className="flex-1" onClick={()=>setRenaming(false)}>Cancel</SecondaryButton><PrimaryButton className="flex-1" disabled={!newName.trim()||rename.isPending} type="submit">Save</PrimaryButton></div></form></div>}</div>;
}

export function AskSession() {
  const router=useRouter();const search=useSearchParams();const docId=search.get("docId")??"";const docName=search.get("docName")??"Document";const server=useAskDocumentMessages(docId);const send=useSendAskDocumentMessage();const [text,setText]=useState("");const [pending,setPending]=useState<{id:string;text:string;createdAt:string}[]>([]);const bottom=useRef<HTMLDivElement>(null);const pendingId=useRef(0);
  const serverItems=useMemo(()=>server.data?.items??[],[server.data]);const visiblePending=useMemo(()=>{const counts=new Map<string,number>();serverItems.filter(m=>m.role==="user").forEach(m=>counts.set(m.text,(counts.get(m.text)??0)+1));return pending.filter(m=>{const count=counts.get(m.text)??0;if(count){counts.set(m.text,count-1);return false;}return true;});},[pending,serverItems]);const messages:AskDocumentMessage[]=[...serverItems,...visiblePending.map(m=>({id:m.id,document_id:docId,role:"user" as const,text:m.text,created_at:m.createdAt}))];const hasUser=messages.some(m=>m.role==="user");
  useEffect(()=>{const timer=window.setTimeout(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),60);return()=>window.clearTimeout(timer);},[messages.length,send.isPending]);
  function submit(value=text){const clean=value.trim();if(!clean||send.isPending)return;pendingId.current+=1;const optimistic={id:`pending-${pendingId.current}`,text:clean,createdAt:new Date().toISOString()};setPending(p=>[...p,optimistic]);setText("");send.mutate({docId,text:clean},{onError:error=>{setPending(p=>p.filter(item=>item.id!==optimistic.id));if(isPremiumRequired(error))router.replace("/paywall");else window.alert(isRateLimited(error)?"Slow down a moment":`Couldn't send: ${getErrorMessage(error)}`);}});}
  return <div className="mx-auto flex min-h-[calc(100vh-10rem)] max-w-3xl flex-col"><Header title="Ask session" subtitle={docName}/><div className="mt-5 flex-1 space-y-5 pb-40"><div className="mx-auto w-fit rounded-full bg-[#EEF2FF] px-4 py-2 text-xs font-black text-[#312E81]">Discussing this doc</div>{server.isLoading&&!serverItems.length?<ChatSkeleton/>:<>{!messages.length&&<AssistantBubble text="Hi, I’ve read your document and I’m ready. Ask me anything about it."/>}{messages.map(message=>message.role==="assistant"?<AssistantBubble key={message.id} text={message.text}/>:<div className="flex justify-end" key={message.id}><div className="max-w-[82%] rounded-2xl rounded-br-md bg-[#312E81] px-4 py-3 text-sm font-semibold leading-6 text-white shadow-sm">{message.text}</div></div>)}{send.isPending&&<div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#FACC15]"><Icon name="spark" className="h-4 w-4"/></span><div className="flex gap-1.5 rounded-2xl bg-white px-4 py-4 shadow-sm"><i className="h-2 w-2 animate-bounce rounded-full bg-slate-400"/><i className="h-2 w-2 animate-bounce rounded-full bg-slate-400 [animation-delay:150ms]"/><i className="h-2 w-2 animate-bounce rounded-full bg-slate-400 [animation-delay:300ms]"/></div></div>}</>}<div ref={bottom}/></div>{!hasUser&&!send.isPending&&<div className="fixed inset-x-0 bottom-36 z-20 flex gap-2 overflow-x-auto px-4 lg:left-72 lg:justify-center">{["Summarize this doc","Key takeaways","Explain the hardest part"].map(item=><button className="shrink-0 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black shadow-sm" key={item} onClick={()=>submit(item)}>{item}</button>)}</div>}<div className="fixed inset-x-0 bottom-[73px] z-20 border-t border-slate-200 bg-white/95 p-3 backdrop-blur lg:bottom-0 lg:left-72"><div className="mx-auto flex max-w-3xl items-end gap-2"><button className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-400" aria-label="Attach another file" type="button"><Icon name="paperclip" className="h-4 w-4"/></button><textarea className="max-h-[120px] min-h-11 flex-1 resize-none rounded-xl border border-slate-200 px-3 py-3 text-sm font-semibold outline-none focus:border-[#312E81]" onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit();}}} placeholder="Ask about this document…" rows={1} value={text}/><button className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#FACC15] disabled:bg-slate-200 disabled:text-slate-400" disabled={!text.trim()||send.isPending} onClick={()=>submit()}><Icon name="arrowUp" className="h-4 w-4"/></button></div></div></div>;
}

function AssistantBubble({text}:{text:string}){return <div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#FACC15] text-[#1E1B4B]"><Icon name="spark" className="h-4 w-4"/></span><div className="max-w-[86%]"><p className="mb-1 text-[10px] font-black tracking-[.16em] text-slate-400">ACELEY</p><div className="whitespace-pre-wrap rounded-2xl rounded-tl-md bg-white px-4 py-3 text-sm font-semibold leading-6 shadow-sm">{text}</div></div></div>;}
function ChatSkeleton(){return <div className="space-y-5" aria-label="Loading conversation"><div className="flex gap-3"><span className="h-9 w-9 animate-pulse rounded-xl bg-slate-200"/><span className="h-24 w-3/4 animate-pulse rounded-2xl bg-slate-200"/></div><div className="flex justify-end"><span className="h-14 w-1/2 animate-pulse rounded-2xl bg-slate-200"/></div><div className="flex gap-3"><span className="h-9 w-9 animate-pulse rounded-xl bg-slate-200"/><span className="h-20 w-2/3 animate-pulse rounded-2xl bg-slate-200"/></div></div>;}
function normalizeFileUrl(url:string){if(!url||url.startsWith("file://"))return null;if(/^https?:\/\//.test(url))return url;const base=(process.env.NEXT_PUBLIC_API_URL??"http://localhost:8000").replace(/\/$/,"");return `${base}${url.startsWith("/")?"":"/"}${url}`;}
function timeAgo(value:string){const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return"just now";if(seconds<3600)return`${Math.floor(seconds/60)}m ago`;if(seconds<86400)return`${Math.floor(seconds/3600)}h ago`;return`${Math.floor(seconds/86400)}d ago`;}
