"use client";import{useMutation,useQuery,useQueryClient}from"@tanstack/react-query";import*as api from"@/services/modules/tutor";
export const tutorSessionsKey=["tutor","sessions","list"]as const;export const tutorSessionKey=(id:string)=>["tutor","sessions",id]as const;export const tutorMessagesKey=(id:string)=>["tutor","sessions",id,"messages"]as const;export const tutorUploadsKey=(id:string)=>["tutor","sessions",id,"uploads"]as const;export const tutorNotesKey=(id:string)=>["tutor","sessions",id,"notes"]as const;
export function useCreateTutorSession(){const c=useQueryClient();return useMutation({mutationFn:api.createTutorSession,onSuccess:s=>{c.setQueryData(tutorSessionKey(s.session_id),s);void c.invalidateQueries({queryKey:tutorSessionsKey});}})}
export const useTutorMessages=(id:string)=>useQuery({queryKey:tutorMessagesKey(id),queryFn:()=>api.getTutorMessages(id),enabled:!!id,staleTime:10_000});
export const useTutorUploads=(id:string)=>useQuery({queryKey:tutorUploadsKey(id),queryFn:()=>api.getTutorUploads(id),enabled:!!id,staleTime:30_000});
export const useTutorNotes=(id:string)=>useQuery({queryKey:tutorNotesKey(id),queryFn:()=>api.getTutorNotes(id),enabled:!!id,staleTime:30_000});
function invalidating<T,V>(fn:(v:V)=>Promise<T>,key:(v:V)=>readonly unknown[]){return function(){const c=useQueryClient();return useMutation({mutationFn:fn,onSuccess:(_,v)=>void c.invalidateQueries({queryKey:key(v)})})}}
export function useSendTutorMessage(){const c=useQueryClient();return useMutation({mutationFn:api.sendTutorSessionMessage,onSuccess:(_,v)=>void c.invalidateQueries({queryKey:tutorMessagesKey(v.sessionId)})})}
export function useUploadTutorFile(){const c=useQueryClient();return useMutation({mutationFn:({sessionId,file}:{sessionId:string;file:File})=>api.uploadTutorFile(sessionId,file),onSuccess:(_,v)=>void c.invalidateQueries({queryKey:tutorUploadsKey(v.sessionId)})})}
export const useDeleteTutorUpload=invalidating(api.deleteTutorUpload,v=>tutorUploadsKey(v.sessionId));export const useCreateTutorNote=invalidating(api.createTutorNote,v=>tutorNotesKey(v.sessionId));export const useDeleteTutorNote=invalidating(api.deleteTutorNote,v=>tutorNotesKey(v.sessionId));
export const useStartTutorQuiz=()=>useMutation({mutationFn:api.startTutorQuiz});export const useUpdateTutorSession=()=>useMutation({mutationFn:api.updateTutorSession});export const useDeleteTutorSession=()=>useMutation({mutationFn:api.deleteTutorSession});
